#!/usr/bin/env node
// ===================================================
// Copies the package's shipped sources into the demo app.
// The copies are gitignored and regenerated by `prestart` and `prebuild`.
// ===================================================

import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const demoRoot = resolve(dirname(fileURLToPath(import.meta.url)));
const packageRoot = resolve(demoRoot, '..');

const COPIES = [
  {
    label: 'catalog',
    from: join(packageRoot, 'src', 'lib'),
    to: join(demoRoot, 'src', 'golemui-kendo'),
  },
  {
    label: 'widget components',
    from: join(packageRoot, 'src', 'ng-add', 'files', 'widgets'),
    to: join(demoRoot, 'src', 'app', 'kendo-widgets'),
  },
];

const HEADER = `// GENERATED FILE - do not edit.
// Copied by demo/sync-sources.mjs. Edit the original under the package's src/.
`;

for (const { label, from, to } of COPIES) {
  rmSync(to, { recursive: true, force: true });
  mkdirSync(to, { recursive: true });
  cpSync(from, to, {
    recursive: true,
    filter: (source) => !source.endsWith('.spec.ts'),
  });
  console.log(`Synced ${label}: ${from} -> ${to}`);
}

// A marker rather than a per-file header, so the copies stay byte-identical to
// what the package ships and a stray edit in demo/ is still easy to spot.
writeFileSync(join(demoRoot, 'src', 'golemui-kendo', 'GENERATED.md'), HEADER);
writeFileSync(join(demoRoot, 'src', 'app', 'kendo-widgets', 'GENERATED.md'), HEADER);
